### PR TITLE
Fix file name rendering

### LINKED ISSUE #85: File names not rendered correctly
image

Each file name should be placed under its island.

### PR DESCRIPTION
**Pull request by algobot76**
Close #85

### CODE REVIEW

File: client/src/components/Island/index.tsx [hunk 1]
```diff
@@ -85,18 +84,17 @@ const Island: React.FC = (props: any) => {
...
 
   return (
-
-    <IslandWithFileName width={fileSizeAdjustedWidth}>
-      <IslandContainer
-        minWidth={fileSizeAdjustedWidth}
-        x={fileAnalysis.topLeftCorner.x}
-        y={fileAnalysis.topLeftCorner.y}
-      >
+    <IslandContainer
```
Comment (MayKikuchi) [inline client/src/components/Island/index.tsx:87]: Instead of flipping IslandWithFileName and IslandContainer, I think the IslandWithFileName should get the x and y positioning

**Comment by MayKikuchi** [comment]
with this, the file name is on top of the island

now
